server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.0.104
    username: leyou
    password: 878132
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.100:10086/eureka
