server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.100:10086/eureka
    registry-fetch-interval-seconds: 10 #指示从eureka服务器获取注册表信息的频率（s）
  instance:
    lease-renewal-interval-in-seconds: 5 #每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 #10秒不发送就过期
    ip-address: 192.168.0.100
    prefer-ip-address: true
ly:
  jwt:
    secret: ly@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: C:/Users/Administrator/Desktop/复习/rsa/rsa.pub # 公钥地址
    priKeyPath: C:/Users/Administrator/Desktop/复习/rsa/rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN

