server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.0.100:3306/yun6
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.0.104
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.100:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    ip-address: 192.168.0.100
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.leyou.order.pojo
ly:
  jwt:
    pubKeyPath: C:/Users/Administrator/Desktop/复习/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workerId: 1
    dataCenterId: 1
  pay:
    appId: wx8397f8696b538317
    mchId: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    connectTimeoutMs: 5000
    readTimeoutMs: 10000
    notifyUrl: http://i5tte3.natappfree.cc/notify/pay