server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.0.104
    username: leyou
    password: 878132
    virtual-host: /leyou
  redis:
    host: 192.168.0.104
ly:
  sms:
    accessKeyId: LTAI0hpzMx52lTAq
    accessKeySecret: ExvgBytoVAmTPC2tfOENeLTvQ8he89
    signName: 乐优
    verifyCodeTemplate: SMS_169900855

